# Site
name: "MakinaRocks Tech Blog"
title: "MakinaRocks Tech Blog"
description: "MakinaRocks Tech Blog"
logo: 'assets/images/makinarocks_logo.png'
favicon: 'assets/images/mrx_logo.png'
url: https://makinarocks.github.io
baseurl: ""
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: contact@makinarocks.ai

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/donate/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
    
  ki hyun kim:
    name: ki hyun kim
    display_name: ki hyun kim
    avatar: 'assets/images/team/kimkihyun.png'
    gravatar: 
    email: 
    web: 
    description: 
    
  wontak ryu:
    name: wontak ryu
    display_name: wontak ryu
    avatar: 'assets/images/team/ryuwontak.png'
    gravatar: 
    email: 
    web: 
    description:

  jemin kim:
    name: jemin kim
    display_name: jemin kim
    avatar: 'assets/images/team/jeminkim.png'
    gravatar:
    email:
    web:
    description:
  
  yuri rocha:
    name: yuri rocha
    display_name: Yuri Rocha
    avatar: 'assets/images/team/yurirocha.png'
    gravatar: 
    email: 
    web: 
    description:

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
