# Site
name: "Yusuf Fahry" # "Memoirs"
title: "Toilet Thoughts" # "Memoirs"
description: "On data, games, and toilet thoughts!" # "I will take you on the fabulous world of exploration. Travel, culture, lifestyle. Eat, Pray, Love!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '' # /jekyll-theme-memoirs
google_analytics: # 'UA-xxxxxxxx-1'
disqus: # 'demowebsite'
mailchimp-list: # 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: cubes08_coir@icloud.com # wowthemesnet@gmail.com

# Authors
authors:
  yusuf:
    name: Yusuf Fahry # Sal
    display_name: Yusuf # Sal
    avatar: 'assets/images/yusuf-avatar.png' # 'assets/images/avatar-sal.png'
    email: cubes08_coir@icloud.com # wowthemesnet@gmail.com
    web: # https://www.wowthemes.net/donate/
    twitter: # https://twitter.com/wowthemesnet
    description: "My world spins around data and games. Currently helping an eSport team to sit on the SEA throne through data and a master student." # "Author of Memoirs, a Bootstrap Medium styled template available for Jekyll. You are currently previewing Jekyll template demo."
  # john:
  #   name: John
  #   display_name: John    
  #   avatar: 'assets/images/avatar.png'
  #   email: wowthemesnet@gmail.com
  #   web: https://www.wowthemes.net
  #   twitter: https://twitter.com/wowthemesnet
  #   description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: # "ca-pub-3412143450191416"
adsense-data-ad-slot: # "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
