# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "assets/images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: true
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured", name: "image", widget: "file" }
      - { label: "Category", name: "categories", widget: "list" }
      - { label: "TOC", name: "toc", widget: "boolean", default: true }
      - { label: "BeforeTOC", name: "beforetoc", widget: "string"}
      - { label: "Author", name: "author", widget: "string"}
      - { label: 'Body', name: 'body', widget: 'markdown' }